apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "wallet.main"

        minSdkVersion 26
        targetSdkVersion 28

        versionCode 1
        versionName "1.0"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                    androidManifestFile: "$projectDir/src/main/AndroidManifest.xml".toString()
                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/androidx/**/LICENSE.txt'
        exclude 'META-INF/*.version'
        exclude 'META-INF/proguard/**'
        exclude 'META-INF/*.kotlin_module'
        exclude 'META-INF/kotlin-project-structure-metadata.json'
        exclude 'META-INF/**/coroutines.pro'
        exclude 'DebugProbesKt.bin'
        exclude '**/*.proto'
    }
}

configurations.all {
    exclude group: 'com.google.code.findbugs', module: 'jsr305'
    exclude group: 'com.google.code.findbugs', module: 'annotations'
    exclude group: 'net.jcip', module: 'jcip-annotations'

    resolutionStrategy {
        force 'com.google.guava:guava:27.0.1-jre'
        force 'org.slf4j:slf4j-api:1.7.36'
    }
}

dependencies {
    // No local JARs are currently present in app/libs.

    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'

    implementation 'org.androidannotations:androidannotations-api:4.6.0'
    annotationProcessor 'org.androidannotations:androidannotations:4.6.0'

    implementation('com.journeyapps:zxing-android-embedded:3.6.0') {
        exclude group: 'com.google.code.findbugs'
        exclude group: 'net.jcip'
        exclude group: 'com.google.guava'
    }

    implementation 'com.google.zxing:core:3.4.1'

    implementation 'com.github.kenglxn.QRGen:android:2.6.0'

    implementation('org.bitcoinj:bitcoinj-core:0.17.1') {
        exclude group: 'com.google.code.findbugs'
        exclude group: 'net.jcip'
        exclude group: 'com.google.guava'
        exclude group: 'org.slf4j'
    }

    implementation 'com.google.protobuf:protobuf-javalite:4.33.4'
    implementation 'com.google.guava:guava:27.0.1-jre'
    implementation 'org.slf4j:slf4j-android:1.7.36'
}
