apply plugin: 'com.android.application'

android {
namespace 'wallet.main'
compileSdkVersion 33

defaultConfig {
    applicationId "wallet.main"

    minSdkVersion 21
    targetSdkVersion 33

    versionCode 1
    versionName "1.0"
}

buildTypes {
    release {
        minifyEnabled true
        shrinkResources true
        crunchPngs false

        proguardFiles getDefaultProguardFile('proguard-android.txt'),
                'proguard-rules.pro'
    }
}

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

packagingOptions {
    exclude 'META-INF/androidx/**/LICENSE.txt'
    exclude 'META-INF/*.version'
    exclude 'META-INF/proguard/**'
    exclude 'META-INF/*.kotlin_module'
    exclude 'META-INF/kotlin-project-structure-metadata.json'
    exclude 'META-INF/**/coroutines.pro'
    exclude 'DebugProbesKt.bin'
    exclude '**/*.proto'
    exclude 'core/**'
    exclude 'kotlin/**'
    exclude 'kotlinx/**'
    exclude 'commonMain/**'
    exclude 'nativeMain/default/**'
    exclude 'nativeOtherMain/default/**'
    exclude 'nonJvmMain/default/**'
    exclude 'concurrentMain/default/**'
    exclude 'linuxMain/default/**'
    exclude 'org/bouncycastle/**/*.properties'
    exclude 'okhttp3/internal/publicsuffix/*'
    exclude 'org/bitcoinj/crypto/mnemonic/wordlist/english.txt'
    exclude 'org/bitcoinj/crypto/cacerts'
    exclude 'org.bitcoin.*.checkpoints.txt'
    }
}

configurations.all {
exclude group: 'com.google.errorprone', module: 'error_prone_annotations'
exclude group: 'com.google.code.findbugs', module: 'jsr305'
exclude group: 'com.google.code.findbugs', module: 'annotations'
exclude group: 'net.jcip', module: 'jcip-annotations'
//exclude group: 'org.slf4j', module: 'slf4j-api'
}

dependencies {
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:recyclerview-v7:28.0.0'
implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
implementation 'com.github.kenglxn.QRGen:android:2.6.0'
implementation 'org.bitcoinj:bitcoinj-core:0.17.1'
implementation 'com.google.protobuf:protobuf-javalite:4.33.4'
implementation 'com.google.guava:guava:33.4.0-android'
implementation 'org.slf4j:slf4j-android:1.7.36'
}
